### ISSUE TITLE
Road Map

### ISSUE THREAD

**Issue by LucaZulberti** [LucaZulberti/contiki-ng#2]
# Porting the WI502 board to Contiki-NG

A list of feature to add will be compiled and updated here.

### Minimal changes to make it run

- [x] change definitions from "CC2538DK" to "WI502"
- [x] update configuration and Makefile
- [x] remove all devices

### New features

- [x] add CC2538 peripheral configuration

## Devices

- [ ] add basic (Buttons, LEDs, ...)
- [ ] add accelerometer
- [ ] add humidity and temperature sensor
- [ ] add light sensor
- [ ] add battery

## Misc

- [ ] make examples work for the new platform
- [ ] update documentation

**Comment by LucaZulberti** [comment]
Changed definitions: e48df80

**Comment by LucaZulberti** [comment]
Updated configuration files and Makefile: 694f0a2

**Comment by LucaZulberti** [comment]
Removed all devices: 7587702

**Comment by LucaZulberti** [comment]
Updated configuration for CC2538 peripherlas: 3b3071d
